version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    env_file:
      - .env.docker

  web:
    build: .
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-w@wh3_ecu9jayqu@!69fawwxjcv!!8r#6-#!8(h(&^@5x9%l+i
      - DEBUG=True
      - ALLOWED_HOSTS='127.0.0.1 localhost web'
      - PG_DATABASE=weather_app
      - PG_USER=postgres
      - PG_PASSWORD=dbsb3272
      - DB_HOST=db
      - DB_PORT=5432
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  postgres_data:
