# Generated by Django 4.2.14 on 2024-07-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_cityweatherrequest_delete_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="cityweatherrequest",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
