# Generated by Django 4.2.14 on 2024-07-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_cityweatherrequest_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cityweatherrequest",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="cityweatherrequest",
            unique_together={("city", "session_key")},
        ),
    ]
